"""Presentation generation workflow steps (DOM-007)."""

from enum import StrEnum


class PresentationWorkflowStep(StrEnum):
    INIT = "init"
    LOAD_PROJECT = "load_project"
    VALIDATE_SOURCES = "validate_sources"
    RETRIEVE_CONTEXT = "retrieve_context"
    EXTRACT_FACTS = "extract_facts"
    VALIDATE_FACTS = "validate_facts"
    BUILD_MANUSCRIPT = "build_manuscript"
    REVIEW_MANUSCRIPT = "review_manuscript"
    BRIEF = "brief"
    REVIEW_BRIEF = "review_brief"
    CULTURAL_NARRATIVE = "cultural_narrative"
    RENOVATION_ISSUE_MAP = "renovation_issue_map"
    REFERENCE_STYLE_PROFILE = "reference_style_profile"
    STORYLINE = "storyline"
    REVIEW_STORYLINE = "review_storyline"
    OUTLINE = "outline"
    REVIEW_OUTLINE = "review_outline"
    REVIEW_SLIDES = "review_slides"
    SLIDES = "slides"
    RESOLVE_CITATIONS = "resolve_citations"
    MATCH_ASSETS = "match_assets"
    CONTENT_REVIEW = "content_review"
    EVIDENCE_REVIEW = "evidence_review"
    ARCHITECTURAL_REVIEW = "architectural_review"
    LAYOUT_REVIEW = "layout_review"
    PROFESSIONAL_REVIEW = "professional_review"
    REPAIR_SLIDES = "repair_slides"
    SLIDE_VALIDATION = "slide_validation"
    EXPORT = "export"
    PRESENTATION_SPEC = "presentation_spec"
    MARP = "marp"
    FINALIZE = "finalize"
    FAILED = "failed"
