"""Domain enumerations package (DOM-018).

Prefer importing from ``archium.domain.enums``; submodules are the split SSOT.
"""

from archium.domain.enums.assets import (
    AssetType,
    SlideAssetBindingRole,
    VisualType,
)
from archium.domain.enums.document import (
    DocumentPurpose,
    DocumentType,
    ProcessingStatus,
    VerificationStatus,
)
from archium.domain.enums.knowledge import (
    AssumptionStatus,
    InformationOrigin,
    InformationReliability,
    KnowledgeGapCategory,
    KnowledgeGapStatus,
    KnowledgeItemStatus,
    QuestionAnswerType,
    QuestionStatus,
    ResolutionMethod,
)
from archium.domain.enums.mission import (
    ConstraintSource,
    DeliverableType,
    EffortLevel,
    InterventionScale,
    Priority,
    ServiceDepth,
    TaskNature,
    UncertaintyLevel,
    WorkstreamStatus,
    WorkstreamType,
)
from archium.domain.enums.presentation import (
    ApprovalStatus,
    DeckDeliveryStatus,
    EvidenceAvailability,
    NarrativeStage,
    OutlineAudienceMode,
    PresentationStatus,
    PresentationType,
    RevisionEntityType,
    RevisionSource,
    SlideChangeSource,
    SlideDeliveryStatus,
    SlideRepairSource,
    SlideRepairTier,
    SlideStatus,
    SlideType,
)
from archium.domain.enums.project import (
    ProjectDomain,
    ProjectStage,
    ProjectStatus,
    ProjectType,
)
from archium.domain.enums.review import (
    PipelineRole,
    ReviewCategory,
    ReviewLayer,
    ReviewSeverity,
    ReviewStatus,
    ValidationSeverity,
)
from archium.domain.enums.workflow import (
    PlanningSessionStatus,
    PlanningWorkflowStep,
    PresentationWorkflowStep,
    SlideRecoveryWorkflowStep,
    VisualWorkflowStep,
    WorkflowStatus,
    WorkflowStep,
)

__all__ = [
    "ProjectType",
    "ProjectStage",
    "ProjectStatus",
    "ProjectDomain",
    "DocumentType",
    "ProcessingStatus",
    "VerificationStatus",
    "DocumentPurpose",
    "InformationOrigin",
    "InformationReliability",
    "KnowledgeItemStatus",
    "KnowledgeGapCategory",
    "KnowledgeGapStatus",
    "ResolutionMethod",
    "AssumptionStatus",
    "QuestionAnswerType",
    "QuestionStatus",
    "NarrativeStage",
    "OutlineAudienceMode",
    "PresentationType",
    "PresentationStatus",
    "ApprovalStatus",
    "EvidenceAvailability",
    "SlideType",
    "SlideStatus",
    "SlideDeliveryStatus",
    "DeckDeliveryStatus",
    "RevisionSource",
    "SlideChangeSource",
    "SlideRepairTier",
    "SlideRepairSource",
    "RevisionEntityType",
    "TaskNature",
    "InterventionScale",
    "ServiceDepth",
    "UncertaintyLevel",
    "Priority",
    "EffortLevel",
    "ConstraintSource",
    "WorkstreamType",
    "WorkstreamStatus",
    "DeliverableType",
    "VisualType",
    "AssetType",
    "SlideAssetBindingRole",
    "PipelineRole",
    "ReviewLayer",
    "ReviewCategory",
    "ReviewSeverity",
    "ValidationSeverity",
    "ReviewStatus",
    "WorkflowStatus",
    "PlanningSessionStatus",
    "WorkflowStep",
    "PresentationWorkflowStep",
    "PlanningWorkflowStep",
    "VisualWorkflowStep",
    "SlideRecoveryWorkflowStep",
]
