"""Seed architecture cases — curated transferable principles (not a brochure DB)."""

from __future__ import annotations

from archium.domain.architecture_case import ArchitectureCase

# Short educational summaries for retrieval / prompt injection only.
ARCHITECTURE_CASE_SEEDS: tuple[ArchitectureCase, ...] = (
    ArchitectureCase(
        id="therme_vals",
        name="Therme Vals",
        architect="Peter Zumthor",
        location="瑞士 Vals",
        year="1996",
        building_type="温泉 / 疗愈",
        context="阿尔卑斯山谷聚落，强调身体与山体关系",
        design_problem="如何让公共疗愈空间成为地貌的延伸，而非景区盒子？",
        strategy="建筑嵌入山体，路径体验主导",
        spatial_logic="序列洞穴式路径；明暗与水声组织节奏",
        material_language="当地片岩层叠",
        atmosphere="静谧、内向、物质沉重",
        transferable_principles=[
            "精神/疗愈类文化建筑可用嵌入与路径代替展示大厅",
            "材料本地性强化场所归属",
        ],
        risks=["造价与工艺门槛高", "过度模仿石材表情易成风格空转"],
        tags=["冥想", "静谧", "嵌入", "路径", "疗愈", "山地", "温泉", "精神空间"],
    ),
    ArchitectureCase(
        id="salk_institute",
        name="Salk Institute",
        architect="Louis Kahn",
        location="美国拉霍亚",
        year="1965",
        building_type="研究 / 庭院",
        context="悬崖面向太平洋",
        design_problem="如何用轴线与空院组织研究共同体与景观对话？",
        strategy="对称研究翼夹持虚空轴线，指向远景",
        spatial_logic="双翼+中央虚空庭院；实验室与会面分层",
        material_language="清水混凝土与柚木",
        atmosphere="庄重、开放、水平延展",
        transferable_principles=[
            "庭院可作为机构公共性的核心，而非装饰绿地",
            "轴线可组织研究/礼仪/景观三层叙事",
        ],
        risks=["对称轴线在复杂坡地需转译", "尺度过大易空旷"],
        tags=["庭院", "轴线", "研究", "开放", "景观", "机构", "水平"],
    ),
    ArchitectureCase(
        id="ningbo_museum",
        name="宁波博物馆",
        architect="王澍",
        location="中国宁波",
        year="2008",
        building_type="博物馆 / 文化",
        context="快速城市化中的地方记忆",
        design_problem="如何让博物馆成为地方建造记忆的容器，而非国际风格展馆？",
        strategy="瓦爿墙与山体意象转译聚落肌理",
        spatial_logic="内部街巷与庭院穿插；展陈与漫游并行",
        material_language="回收砖瓦、竹模混凝土",
        atmosphere="粗粝、在地、漫游",
        transferable_principles=[
            "材料回收可承载文化叙事，而不只是立面装饰",
            "文化建筑可用街巷化路径替代单一大厅",
        ],
        risks=["材料工艺依赖地方供应链", "形式语言强时需防止盖过展陈内容"],
        tags=["文化中心", "博物馆", "在地", "街巷", "庭院", "材料", "记忆", "聚落"],
    ),
    ArchitectureCase(
        id="louisiana_museum",
        name="Louisiana Museum",
        architect="Jørgen Bo / Vilhelm Wohlert",
        location="丹麦 Humlebæk",
        year="1958+",
        building_type="美术馆",
        context="滨海林园",
        design_problem="如何让观展成为与自然连续的漫游体验？",
        strategy="低平廊道串联展厅与景观",
        spatial_logic="线性漫游；室内外界面渗透",
        material_language="白墙、木作、玻璃",
        atmosphere="轻、连续、园林感",
        transferable_principles=[
            "文化设施可用廊道组织展陈，减少纪念碑式体量",
            "景观渗透可成为展陈叙事的一部分",
        ],
        risks=["气候界面与能耗需控制", "过分散布增加管理成本"],
        tags=["漫游", "景观渗透", "美术馆", "轻介入", "廊道", "自然"],
    ),
    ArchitectureCase(
        id="rural_courtyard_type",
        name="关中/北方合院聚落类型（综合）",
        architect="（类型学）",
        location="中国北方",
        year="传统",
        building_type="民居 / 公共转译",
        context="农耕聚落与家族生活",
        design_problem="如何用内向院落组织日常生活与礼仪，同时适应当代公共性？",
        strategy="围合院落分层公私；入口序列控制",
        spatial_logic="门—院—堂层次；侧厢辅助",
        material_language="生土、砖木",
        atmosphere="内聚、日常、礼仪",
        transferable_principles=[
            "院落可同时服务日常停留与礼仪仪式",
            "内向聚合可转译当代社区公共核",
        ],
        risks=["直接复刻合院尺度不适当代消防与停车", "礼仪轴需与后勤分流"],
        tags=["院落", "合院", "社区", "礼仪", "乡村", "文化中心", "内向", "日常"],
    ),
    ArchitectureCase(
        id="terrace_settlement",
        name="山地台地聚落类型（综合）",
        architect="（类型学）",
        location="东亚山地",
        year="传统—当代",
        building_type="聚落 / 公共",
        context="坡地耕作与分层公共",
        design_problem="如何在坡地上组织可达公共空间，避免削平地貌？",
        strategy="顺等高线分层台地；公共核落在转折台层",
        spatial_logic="台地层级+踏步/坡道串联；观景与日常并置",
        material_language="石坎、木构、当地砌筑",
        atmosphere="层叠、开放、地貌共生",
        transferable_principles=[
            "山地文化建筑宜用台地组织公共性，而非单一大平台",
            "垂直高差可转化为观景与社区交往界面",
        ],
        risks=["无障碍通行成本高", "台地过多导致流线碎片化"],
        tags=["山地", "台地", "聚落", "文化中心", "等高线", "嵌入", "坡地", "社区"],
    ),
    ArchitectureCase(
        id="sendai_mediatheque",
        name="仙台媒体中心",
        architect="Toyo Ito",
        location="日本仙台",
        year="2001",
        building_type="媒体 / 公共文化",
        context="城市中心多世代公共",
        design_problem="如何让文化设施减少机构感，支持混合使用与透明公共性？",
        strategy="管状结构创造自由平面与视线穿透",
        spatial_logic="多层连续；功能松散叠合",
        material_language="钢、玻璃",
        atmosphere="轻、透明、都市",
        transferable_principles=[
            "公共文化空间可强调通透与混合，降低机构化感觉",
            "结构逻辑可同时服务空间自由与象征",
        ],
        risks=["透明性带来隐私与眩光问题", "运营需支持多功能切换"],
        tags=["公共", "媒体", "透明", "混合", "城市", "年轻", "文化中心", "非机构化"],
    ),
    ArchitectureCase(
        id="bruder_klaus",
        name="Bruder Klaus Field Chapel",
        architect="Peter Zumthor",
        location="德国 Mechernich",
        year="2007",
        building_type="小教堂 / 冥想",
        context="田野中的精神节点",
        design_problem="如何用极小体量创造强烈精神体验？",
        strategy="浇筑后烧失木模，留下焦黑内腔",
        spatial_logic="单一洞穴；天光作为唯一导向",
        material_language="混凝土、木炭痕迹",
        atmosphere="原始、冥想、垂直",
        transferable_principles=[
            "冥想空间可跨宗教类型迁移：压缩、光、物质痕迹",
            "极小建筑可通过构造叙事获得场所力量",
        ],
        risks=["不可直接复制仪式语境", "舒适性与无障碍受限"],
        tags=["冥想", "静谧", "精神空间", "极小", "光", "构造", "纪念"],
    ),
)


def all_seed_cases() -> list[ArchitectureCase]:
    return list(ARCHITECTURE_CASE_SEEDS)
