"""Shim: scene font policy lives in domain; FS probe wired in infrastructure."""

from archium.infrastructure.layout.scene_fonts import (
    CJK_FALLBACK_CHAIN,
    DEFAULT_CJK_FONT,
    DEFAULT_LATIN_FONT,
    LATIN_FALLBACK_CHAIN,
    ResolvedTextFonts,
    cjk_latin_from_typography,
    collect_font_assets,
    collect_font_assets_from_scene,
    css_font_stack,
    detect_font_fallbacks,
    family_file_available,
    first_available_family,
    preferred_would_be_latin_only,
    repair_scene_fonts,
    repair_text_node_fonts,
    resolve_text_fonts,
    text_has_cjk,
    text_script,
    typography_role_for_semantic,
)

__all__ = [
    "CJK_FALLBACK_CHAIN",
    "DEFAULT_CJK_FONT",
    "DEFAULT_LATIN_FONT",
    "LATIN_FALLBACK_CHAIN",
    "ResolvedTextFonts",
    "cjk_latin_from_typography",
    "collect_font_assets",
    "collect_font_assets_from_scene",
    "css_font_stack",
    "detect_font_fallbacks",
    "family_file_available",
    "first_available_family",
    "preferred_would_be_latin_only",
    "repair_scene_fonts",
    "repair_text_node_fonts",
    "resolve_text_fonts",
    "text_has_cjk",
    "text_script",
    "typography_role_for_semantic",
]
