"""Seed catalog for the Presentation Technology Radar."""

from __future__ import annotations

from archium.domain.external_presentation_system import ExternalPresentationSystem

DEFAULT_RADAR_SYSTEMS: tuple[ExternalPresentationSystem, ...] = (
    ExternalPresentationSystem(
        id="pptagent",
        name="PPTAgent / DeepPresenter",
        repository_url="https://github.com/icip-cas/PPTAgent",
        category="research",
        input_modes=["文档", "大纲", "参考 PPT"],
        output_formats=["PPTX", "PDF"],
        editable_pptx=True,
        agentic_workflow=True,
        document_grounding=True,
        page_model="多步推理 + 模板归纳",
        layout_engine="参考页结构复用",
        template_system="模板归纳 + 反思式生成",
        edit_model="提案式局部编辑",
        qa_model="生成后反思",
        archium_relevance="adopt",
        concepts_to_adopt=[
            "多步骤推理与反思式生成",
            "模板归纳而非硬编码版式",
            "参考页结构提取",
        ],
        concepts_to_avoid=[
            "黑盒整页 raster 输出",
            "无审计链的自动改写",
        ],
    ),
    ExternalPresentationSystem(
        id="presenton",
        name="Presenton",
        repository_url="https://github.com/presenton/presenton",
        category="open_source",
        input_modes=["主题", "大纲", "文档"],
        output_formats=["PPTX", "HTML"],
        editable_pptx=True,
        local_llm=True,
        agentic_workflow=True,
        page_model="Slide / Scene 对象模型",
        layout_engine="程序化布局",
        template_system="可扩展模板",
        edit_model="结构化 Scene 编辑",
        qa_model="渲染一致性检查",
        archium_relevance="trial",
        concepts_to_adopt=[
            "统一 Scene 模型驱动多渲染器",
            "本地 LLM 可选部署",
        ],
        concepts_to_avoid=[
            "直接照搬其 Scene schema",
            "忽略建筑图纸保护规则",
        ],
    ),
    ExternalPresentationSystem(
        id="presentation-ai",
        name="presentation-ai",
        repository_url="https://github.com/allweonedev/presentation-ai",
        category="open_source",
        input_modes=["自然语言", "工具调用"],
        output_formats=["PPTX", "在线预览"],
        editable_pptx=True,
        agentic_workflow=True,
        page_model="工具调用 + 结构化编辑",
        layout_engine="组件化布局",
        template_system="可组合 slide 组件",
        edit_model="Before/After 提案",
        qa_model="用户确认替换",
        archium_relevance="adopt",
        concepts_to_adopt=[
            "AI 工具调用驱动编辑",
            "Before/After 提案与显式接受",
            "结构化 slide 操作",
        ],
        concepts_to_avoid=[
            "绕过 SceneRevision 直接改文件",
        ],
    ),
    ExternalPresentationSystem(
        id="slide-deck-ai",
        name="slide-deck-ai",
        repository_url="https://github.com/barun-saha/slide-deck-ai",
        category="open_source",
        input_modes=["主题", "叙事弧线"],
        output_formats=["PPTX"],
        editable_pptx=True,
        document_grounding=False,
        page_model="阶段契约 + 叙事弧线",
        layout_engine="真实 PPTX 模板",
        template_system="离线模板文件",
        edit_model="有限局部编辑",
        qa_model="导出容错",
        archium_relevance="adopt",
        concepts_to_adopt=[
            "简洁阶段契约",
            "叙事弧线驱动页序",
            "真实 PPTX 模板与容错导出",
        ],
        concepts_to_avoid=[
            "过度复杂的单步生成",
        ],
    ),
    ExternalPresentationSystem(
        id="slidebot-ai",
        name="SlideBot-AI",
        category="saas",
        input_modes=["逐页引导", "素材绑定"],
        output_formats=["PPTX", "在线"],
        editable_pptx=True,
        agentic_workflow=True,
        page_model="逐页状态机",
        layout_engine="页级模板",
        template_system="引导式工作流",
        edit_model="单页重试",
        qa_model="页级状态回显",
        archium_relevance="adopt",
        concepts_to_adopt=[
            "逐页素材绑定",
            "逐页状态与单页重试",
            "引导式工作流",
        ],
        concepts_to_avoid=[
            "整 deck 一次生成不可恢复",
        ],
    ),
    ExternalPresentationSystem(
        id="slideweaver",
        name="Slideweaver",
        category="open_source",
        input_modes=["结构化内容", "布局描述"],
        output_formats=["PPTX"],
        editable_pptx=True,
        page_model="原生对象优先",
        layout_engine="程序化布局",
        template_system="布局原语",
        edit_model="形状级编辑",
        qa_model="渲染 QA + 文件完整性",
        archium_relevance="adopt",
        concepts_to_adopt=[
            "程序化布局与原生对象",
            "导出后渲染 QA",
            "文件完整性验证",
        ],
        concepts_to_avoid=[
            "默认 raster 整页",
        ],
    ),
    ExternalPresentationSystem(
        id="aippt",
        name="AIPPT",
        product_url="https://www.aippt.cn",
        category="saas",
        input_modes=["主题", "文档", "图片"],
        output_formats=["PPTX", "PDF", "图片"],
        editable_pptx=False,
        agentic_workflow=True,
        page_model="整页生成 + 版本历史",
        layout_engine="云端模板",
        template_system="SaaS 模板库",
        edit_model="单页版本替换",
        qa_model="视觉预览",
        archium_relevance="trial",
        concepts_to_adopt=[
            "单页版本历史与确认替换",
            "Image-to-Editable 思路（独立工具化）",
        ],
        concepts_to_avoid=[
            "图片式 PPTX 冒充可编辑",
            "直接接入主生成链",
        ],
    ),
    ExternalPresentationSystem(
        id="beautiful-ai",
        name="Beautiful.ai",
        product_url="https://www.beautiful.ai",
        category="saas",
        input_modes=["主题", "要点"],
        output_formats=["PPTX", "PDF", "在线"],
        editable_pptx=True,
        office_integration=True,
        page_model="智能布局约束",
        layout_engine="自动排版引擎",
        template_system="设计系统驱动",
        edit_model="拖拽 + 智能重排",
        qa_model="设计规则",
        archium_relevance="assess",
        concepts_to_adopt=[
            "布局约束与设计系统",
            "自动重排保持视觉一致",
        ],
        concepts_to_avoid=[
            "通用 SaaS 模板直接套建筑图纸",
        ],
    ),
    ExternalPresentationSystem(
        id="plus-ai",
        name="Plus AI",
        product_url="https://plusai.com",
        category="saas",
        input_modes=["Google Slides", "文档"],
        output_formats=["Google Slides", "PPTX"],
        editable_pptx=True,
        office_integration=True,
        page_model="插件内生成",
        layout_engine="Slides 原生",
        template_system="Google 生态",
        edit_model="侧边栏编辑",
        qa_model="有限",
        archium_relevance="hold",
        concepts_to_adopt=[
            "Office 生态内嵌体验",
        ],
        concepts_to_avoid=[
            "依赖 Google 生态",
            "建筑专业语义不足",
        ],
    ),
    ExternalPresentationSystem(
        id="microsoft-copilot",
        name="Microsoft Copilot (PowerPoint)",
        product_url="https://www.microsoft.com/microsoft-copilot",
        category="office_addin",
        input_modes=["自然语言", "文档", "企业数据"],
        output_formats=["PPTX"],
        editable_pptx=True,
        office_integration=True,
        agentic_workflow=True,
        document_grounding=True,
        page_model="Office 原生对象",
        layout_engine="PowerPoint 布局",
        template_system="企业模板",
        edit_model="Copilot 对话编辑",
        qa_model="企业合规",
        archium_relevance="assess",
        concepts_to_adopt=[
            "Office 原生对象与合规",
            "企业文档接地",
        ],
        concepts_to_avoid=[
            "黑盒替换建筑图纸",
            "无审计的企业生成",
        ],
    ),
    ExternalPresentationSystem(
        id="gamma",
        name="Gamma",
        product_url="https://gamma.app",
        category="saas",
        input_modes=["主题", "大纲", "文档"],
        output_formats=["网页", "PPTX", "PDF"],
        editable_pptx=False,
        agentic_workflow=True,
        page_model="卡片 / 网页优先",
        layout_engine="响应式卡片",
        template_system="主题包",
        edit_model="块级编辑",
        qa_model="在线预览",
        archium_relevance="trial",
        concepts_to_adopt=[
            "叙事块与卡片化结构",
            "快速原型与分享",
        ],
        concepts_to_avoid=[
            "网页卡片模型替代 RenderScene",
            "建筑图纸页降级为截图",
        ],
    ),
)
