#!/bin/bash
# Git 提交指南 - 2026-07-19 集成修复和仓库清理
#
# 本脚本提供分步提交建议，不自动执行
# 请在 Windows host 环境手动执行

echo "======================================"
echo "Git 提交指南"
echo "======================================"
echo ""
echo "当前有以下修改需要提交："
echo ""

echo "## 1. E2E Benchmark API 修复"
echo ""
echo "git add archium/application/visual/e2e_benchmark_service.py"
echo "git commit -m \"fix(e2e-benchmark): 修复 API 不匹配问题，使代码可运行"
echo ""
echo "修复内容："
echo "- 使用正确的 IngestionService.import_file() API"
echo "- 使用 LayoutPlanRepository.get() 获取布局计划"
echo "- 使用 DesignSystemRepository 加载设计系统"
echo "- 补充完整流程：Project → Import → Presentation → SlideSpec"
echo "- 添加 _create_slides_from_case() 辅助方法"
echo ""
echo "当前状态：E2E Lite（简化版本），Phase 2/3 待实现"
echo "\""
echo ""

echo "## 2. 交互式画布集成"
echo ""
echo "git add archium/ui/pages/studio.py"
echo "git commit -m \"feat(studio): 集成交互式画布编辑器"
echo ""
echo "修改内容："
echo "- Studio 主页面切换到 slide_canvas_enhanced"
echo "- 启用 use_interactive_canvas=True 参数"
echo ""
echo "功能："
echo "- 点击选择元素"
echo "- 悬停高亮"
echo "- 元素边界可视化（彩色编码）"
echo "- 元素标签和锁定状态显示"
echo ""
echo "注意：需要构建前端组件（cd archium/ui/components/canvas_editor && bash build.sh）"
echo "\""
echo ""

echo "## 3. Enhanced Deck Composition 集成"
echo ""
echo "git add archium/workflow/visual_nodes.py"
echo "git commit -m \"feat(visual-workflow): 切换到 Enhanced Deck Composition 服务"
echo ""
echo "修改内容："
echo "- VisualWorkflowRuntime 使用 EnhancedDeckCompositionPlanningService"
echo "- 导入增强版服务"
echo ""
echo "增强功能："
echo "- DeckQA 反馈集成"
echo "- 视觉强度曲线分析"
echo "- 章节语义分析"
echo "- 模式识别"
echo "- LLM 语义理解"
echo "\""
echo ""

echo "## 4. 文档整理"
echo ""
echo "git add docs/ organize_docs.sh"
echo "git commit -m \"chore(docs): 整理根目录文档到分类目录"
echo ""
echo "整理内容："
echo "- 将 43 个 markdown 文件整理到 docs/ 子目录"
echo "- 根目录保留 5 个项目级文档（减少 88%）"
echo "- 创建分类目录：sessions, analysis, implementation, delivery, architecture, guides"
echo "- 添加 organize_docs.sh 自动整理脚本"
echo ""
echo "目录结构："
echo "- docs/sessions/2026-07-19/ - 今天的会话记录"
echo "- docs/analysis/ - 问题分析文档"
echo "- docs/implementation/ - 实现和修复文档"
echo "- docs/delivery/ - 交付和总结文档"
echo "- docs/architecture/ - 架构设计文档"
echo "- docs/guides/ - 指南和计划文档"
echo "\""
echo ""

echo "## 5. SQLite WAL 忽略规则（如果还未提交）"
echo ""
echo "git add .gitignore"
echo "git commit -m \"chore(gitignore): 忽略 SQLite WAL/SHM 临时文件"
echo ""
echo "添加规则："
echo "- *.db-wal"
echo "- *.db-shm"
echo "- data/database/*.db-wal"
echo "- data/database/*.db-shm"
echo "\""
echo ""

echo "## 6. 其他修改（GitHub 配置等）"
echo ""
echo "git add .github/"
echo "git commit -m \"chore(github): 更新 GitHub 配置模板"
echo ""
echo "或者单独提交："
echo "git add CODE_OF_CONDUCT.md CONTRIBUTING.md"
echo "git commit -m \"docs: 更新社区文档\""
echo ""

echo "======================================"
echo "推荐提交顺序"
echo "======================================"
echo ""
echo "1. E2E Benchmark 修复（功能修复）"
echo "2. Canvas 集成（功能增强）"
echo "3. Enhanced Deck 集成（功能增强）"
echo "4. 文档整理（仓库清理）"
echo "5. .gitignore 更新（配置修复）"
echo "6. 其他修改（配置更新）"
echo ""

echo "======================================"
echo "验证建议"
echo "======================================"
echo ""
echo "提交前验证："
echo "1. 运行测试"
echo "   pytest tests/unit/visual/test_e2e_benchmark_service.py"
echo "   pytest tests/unit/visual/test_enhanced_deck_composition.py"
echo ""
echo "2. 检查语法"
echo "   python -m py_compile archium/application/visual/e2e_benchmark_service.py"
echo "   python -m py_compile archium/workflow/visual_nodes.py"
echo ""
echo "3. 运行 linter"
echo "   ruff check archium/"
echo ""

echo "======================================"
echo "注意事项"
echo "======================================"
echo ""
echo "1. 这些命令需要在 Windows host 环境执行"
echo "   （VM 中的 Git 有权限问题）"
echo ""
echo "2. 推荐使用 Git GUI 或 VS Code 检查修改"
echo "   确认没有遗漏或多余的修改"
echo ""
echo "3. 如果某个修改不确定，可以先 stash"
echo "   git stash push -m \"暂存不确定的修改\""
echo ""
echo "4. 提交后创建 Pull Request 进行代码审查"
echo ""

echo "======================================"
echo "完成！"
echo "======================================"
