#!/usr/bin/env python3
"""Compile pinned requirement locks from pyproject.toml.

Uses ``uv`` exclusively (do not also maintain Poetry / pip-tools lock flows).

Outputs:
  requirements/base.lock          — core package dependencies only
  requirements/full-py311.lock    — ``.[full]`` resolved for CPython 3.11
  requirements/full-py312.lock    — ``.[full]`` resolved for CPython 3.12

Regenerate after changing ``[project]`` / ``[project.optional-dependencies]``::

    python scripts/compile_requirement_locks.py

Verify committed locks match pyproject (CI / pre-push)::

    python scripts/compile_requirement_locks.py --check
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
_REQ_DIR = _ROOT / "requirements"
_PYPROJECT = _ROOT / "pyproject.toml"


def _uv_cmd() -> list[str]:
    uv = shutil.which("uv")
    if uv:
        return [uv]
    try:
        subprocess.run(
            [sys.executable, "-m", "uv", "--version"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise SystemExit(
            "uv is required to compile requirement locks.\n"
            "Install once with:  pip install uv\n"
            "Then re-run:        python scripts/compile_requirement_locks.py"
        ) from exc
    return [sys.executable, "-m", "uv"]


def _run_uv(args: list[str]) -> None:
    cmd = [*_uv_cmd(), *args]
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True, cwd=_ROOT)


# Resolve as Linux so Windows/macOS hosts produce the same locks as ubuntu CI.
# Without this, markers like ``sys_platform == "win32"`` (e.g. pywin32-ctypes)
# and Linux-only deps (e.g. uvloop) diverge across developers' machines.
_LOCK_PYTHON_PLATFORM = "x86_64-unknown-linux-gnu"


def _stable_header(relative_out: str, *, extra_full: bool, python_version: str) -> str:
    """Header with repo-relative paths so CI temp compiles compare cleanly."""
    extra = " --extra full" if extra_full else ""
    return (
        "# This file was autogenerated by uv via the following command:\n"
        f"#    uv pip compile pyproject.toml{extra}"
        f" --python-version {python_version}"
        f" --python-platform {_LOCK_PYTHON_PLATFORM}"
        f" -o {relative_out}\n"
    )


def _lock_body(text: str) -> str:
    """Drop uv autogen `#` header; keep package pins + via comments."""
    lines = text.splitlines(keepends=True)
    i = 0
    while i < len(lines) and lines[i].lstrip().startswith("#"):
        i += 1
    return "".join(lines[i:])


def _write_lock(
    dest: Path,
    *,
    relative_out: str,
    extra_full: bool,
    python_version: str,
) -> Path:
    """Compile into a fresh temp file, then install with a stable header.

    Compiling directly over an existing lock can make ``uv`` reuse old pins.
    """
    dest.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="archium-lock-out-") as tmp:
        tmp_path = Path(tmp) / dest.name
        args = ["pip", "compile", str(_PYPROJECT)]
        if extra_full:
            args.extend(["--extra", "full"])
        args.extend(
            [
                "--python-version",
                python_version,
                "--python-platform",
                _LOCK_PYTHON_PLATFORM,
                "-o",
                str(tmp_path),
            ]
        )
        _run_uv(args)
        body = _lock_body(tmp_path.read_text(encoding="utf-8"))
        dest.write_text(
            _stable_header(relative_out, extra_full=extra_full, python_version=python_version)
            + body,
            encoding="utf-8",
            newline="\n",
        )
    return dest


def compile_locks(
    *,
    python_versions: tuple[str, ...],
    output_dir: Path,
) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    # When writing into requirements/, use stable relative header paths.
    # For temp check dirs, still emit the same relative names so comparison works.
    base_name = "base.lock"
    base_out = output_dir / base_name
    _write_lock(
        base_out,
        relative_out=f"requirements/{base_name}",
        extra_full=False,
        python_version="3.11",
    )
    written.append(base_out)

    for version in python_versions:
        tag = version.replace(".", "")
        name = f"full-py{tag}.lock"
        out = output_dir / name
        _write_lock(
            out,
            relative_out=f"requirements/{name}",
            extra_full=True,
            python_version=version,
        )
        written.append(out)
    return written


def check_locks(*, python_versions: tuple[str, ...]) -> int:
    """Recompile into a temp dir and fail if committed locks differ."""
    expected = ["base.lock", *[f"full-py{v.replace('.', '')}.lock" for v in python_versions]]
    missing = [name for name in expected if not (_REQ_DIR / name).is_file()]
    if missing:
        print("Missing lock files:", ", ".join(missing), file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="archium-locks-") as tmp:
        tmp_dir = Path(tmp)
        compile_locks(python_versions=python_versions, output_dir=tmp_dir)
        drift: list[str] = []
        for name in expected:
            committed = (_REQ_DIR / name).read_text(encoding="utf-8")
            fresh = (tmp_dir / name).read_text(encoding="utf-8")
            if committed != fresh:
                drift.append(name)
        if drift:
            print(
                "Requirement lock drift detected (pyproject.toml vs requirements/):\n  "
                + "\n  ".join(drift)
                + "\nRegenerate with: python scripts/compile_requirement_locks.py",
                file=sys.stderr,
            )
            return 1
    print("Requirement locks are in sync with pyproject.toml")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--python-version",
        action="append",
        dest="python_versions",
        default=None,
        help="CPython version for full locks (repeatable). Default: 3.11 and 3.12.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if committed locks are out of sync with pyproject.toml.",
    )
    args = parser.parse_args(argv)
    versions = tuple(args.python_versions or ("3.11", "3.12"))
    if args.check:
        return check_locks(python_versions=versions)
    compile_locks(python_versions=versions, output_dir=_REQ_DIR)
    print(f"Wrote locks under {_REQ_DIR.relative_to(_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
